# Generated by Django 3.1.5 on 2021-01-31 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaplanet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tamaño',
            new_name='Tamano',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='tamaño',
            new_name='tamano',
        ),
    ]
