# Generated by Django 3.1.5 on 2021-02-03 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaplanet', '0002_auto_20210131_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='comentario',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='bebida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzaplanet.bebida'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzaplanet.delivery'),
        ),
    ]
