# Generated by Django 3.1.5 on 2021-02-03 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaplanet', '0003_auto_20210203_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='pedido',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pizzaplanet.pedido'),
            preserve_default=False,
        ),
    ]
