# Generated by Django 3.1.5 on 2021-02-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaplanet', '0004_pizza_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateTimeField(null=True, verbose_name='Fecha pedido'),
        ),
    ]
