# Generated by Django 3.1.5 on 2021-02-03 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaplanet', '0005_auto_20210203_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='tamano',
            new_name='tamano_id',
        ),
    ]
