# Generated by Django 3.1.5 on 2021-02-04 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaplanet', '0006_auto_20210203_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='bebida',
        ),
        migrations.CreateModel(
            name='Bebida_pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzaplanet.bebida')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzaplanet.pedido')),
            ],
        ),
    ]
